version: 0.0.1-ci-{branch}-{build}
image: Visual Studio 2019
configuration: Release
platform:
- x64
- Win32
shallow_clone: true
build:
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    7z a -t7z -mx -ms=on %APPVEYOR_PROJECT_NAME%_trunk_%PLATFORM%.7z .\%PLATFORM%\*.exe .\%PLATFORM%\*.dll .\README.md

    7z a -tzip -mx -mm=deflate -mpass=15 %APPVEYOR_PROJECT_NAME%_trunk_%PLATFORM%.zip .\%PLATFORM%\*.exe .\%PLATFORM%\*.dll .\README.md

    7z a -p%APPVEYOR_PROJECT_NAME% -mhe=on -t7z -mx -ms=on %APPVEYOR_PROJECT_NAME%_trunk_password_%PLATFORM%.7z .\%PLATFORM%\*.exe .\%PLATFORM%\*.dll .\README.md

    7z a -p%APPVEYOR_PROJECT_NAME% -tzip -mx -mm=deflate -mpass=15 %APPVEYOR_PROJECT_NAME%_trunk_password_%PLATFORM%.zip .\%PLATFORM%\*.exe .\%PLATFORM%\*.dll .\README.md
artifacts:
- path: $(APPVEYOR_PROJECT_NAME)_trunk_*